### PR TITLE
Derive `Debug` and `Clone` for `MstlParams`

### PR DESCRIPTION
**Pull request by sd2k**
Similar to #5.

### CODE REVIEW

**Comment by ankane** [comment]
Thanks @sd2k, think it makes sense to do for `MstlParams`, but shouldn't be needed for the unit structs.

**Comment by sd2k** [comment]
Happy to remove that if you want, I was mostly following the [debuggability API guidelines](https://rust-lang.github.io/api-guidelines/debuggability.html). I guess it bloats the code slightly?

**Comment by ankane** [comment]
Let's remove it.

**Comment by sd2k** [comment]
@ankane Done, good to go now 👍

**Comment by ankane** [comment]
Thanks @sd2k! Will try to get a release out in the next hour.

**Pull request merged**
